name: Deploy to heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: 'd75b5c3a-bbd2-44e5-83c4-efc6edb7c40b'
          heroku_app_name: 'dogggye'
          email: 'tclone264@gmail.com'
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web